let prefix = 'https://service.narvii.com/api';

export default  {
    login: prefix + '/v1/g/s/auth/login',
    getMe: prefix + '/v1/g/s/account',
    webSocket: (signbody) => `wss://ws1.narvii.com/?signbody=${signbody}`,
    getJoinedComs: (size)=> `${prefix}/v1/g/s/community/joined?start=0&size=${size}`,
    upload: prefix + '/v1/g/s/media/upload',
    linkResolution: (q) => `${prefix}/v1/g/s/link-resolution?q=${q}`,
    getJoinedChats: (com, size) => `${prefix}/v1/x${com}/s/chat/thread?&type=joined-me&start=0&size=${size}`,
    loadChat: (com, uuid, count) => `${prefix}/v1/${com}/s/chat/thread/${uuid}/message?start=0&size=${count}&cv=v1.2`,
    loadChatTwo: (com, uuid, count) => `${prefix}/v1/${com}/s/chat/thread/${uuid}/message?start=100&size=${count}&cv=v1.2`,
    postBlog: (com) => `${prefix}/v1/${com}/s/blog/`,
    deleteBlog: (com, id) => `${prefix}/v1/${com}/s/blog/${id}`,
    commentsPost: (com, id, sort, start, size) => `${prefix}/v1/${com}/s/blog/${id}/comment?sort=${sort}&start=${start}&size=${size}`,
    commentPost: (com, id) => `${prefix}/v1/${com}/s/blog/${id}/comment`,
    sendChat: (com, uuid) => `${prefix}/v1/x${com}/s/chat/thread/${uuid}/message`,
    getUserBlogs: (com, uuid, count) => `${prefix}/v1/${com}/s/blog?type=user&q=${uuid}&start=0&size=${count}`,
    getCommunityBlogFeed: (com, startAt, size) => `${prefix}/v1/${com}/s/feed/blog-all?start=${startAt}&size=${size}`,
    checkIfWikiCanPost: (com, uuid) => `${prefix}/v1/${com}/s/user-profile/${uuid}/compose-eligible-check?objectType=item`,
    createWiki: (com) => `${prefix}/v1/${com}/s/item`,
    deleteWiki: (com, uid) => `${prefix}/v1/${com}/s/item/${uid}`,
    commentWiki: (com, uid) => `${prefix}/v1/${com}/s/item/${uid}/comment`,
    visitProfile: (com, uid) => `${prefix}/v1/${com}/s/user-profile/${uid}?action=visit`,
    commentUser: (com, uid) => `${prefix}/v1/${com}/s/user-profile/${uid}/comment`,
    joinChat: (community, chatId, userId) => `https://service.narvii.com/api/v1/${community}/s/chat/thread/${chatId}/member/${userId}`,
    leaveChat: (com, chatId, userId) => `https://service.narvii.com/api/v1/${com}/s/chat/thread/${chatId}/member/${userId}`,
    deleteMsg: (com, chat, msg) => `${prefix}/v1/${com}/s/chat/thread/${chat}/message/${msg}`,
    getDataProfile: (com, uid) => `${prefix}/v1/${com}/s/user-profile/${uid}`,
    getChatMembers: (com, uid, start, count) => `${prefix}/v1/${com}/s/chat/thread/${uid}/member?type=default&start=${start}&size=${count}`,
    searchCommunity: (q) => `${prefix}/v1/g/s/search/amino-id-and-link?q=${q}`,
    joinCommunity: (comId) => `${prefix}/v1/${comId}/s/community/join`,
    leaveCommunity: (comId) => `${prefix}/v1/${comId}/s/community/leave`,

};